### ISSUE TITLE
Issue with PGMORL logging global_step

### ISSUE THREAD

**Issue by adamcallaghan0** [LucasAlegre/morl-baselines#106]
It does not appear that the "global_step" variable is iterated in the training loop.  Should it be incremented by the sum of copied_agents.global_step each iteration.  

On completion of a run I am unable to generate eum vs global step plots as there is only one global_step data point (with global step value = 0).

![pgmorl](https://github.com/user-attachments/assets/bbb4edc5-e11f-4756-bbb6-f918f5e3bb81)

**Comment by ffelten** [comment]
Hi,

If I remember correctly, `global_step` is incremented by MOPPO.

**Comment by ffelten** [comment]
Hi @adamcallaghan0,

I just ran some experiments with PGMORL, it seems you are right. I'll try to fix it along with the gymnasium 1.0 migration

**Comment by adamcallaghan0** [comment]
Thank you!  In the meantime I have implemented a minor fix on my end to change the warmup block in the train function to: 
![image](https://github.com/user-attachments/assets/9971b561-dafa-4cbf-9f19-259df2eed792)
and slightly further down - 
![image](https://github.com/user-attachments/assets/c811dc96-ad79-476d-a3a5-8a166d926e8b)
This appears to be working correctly now.

**Comment by ffelten** [comment]
I have a concern with this right now:
`self.__train_all_agents` trains for all agents in the population (usually 6).
So I think we should increment by `self.steps_per_iteration * self.nums_envs * len(self.agents)`

Now I have to double-check this but it seems that the implementation has been bugged so far, and performances are even worse than what we reported so far.

**Comment by ffelten** [comment]
Here is what I have so far:
https://github.com/LucasAlegre/morl-baselines/blob/chore/update-gymnasium-1.0/morl_baselines/multi_policy/pgmorl/pgmorl.py#L510

**Comment by adamcallaghan0** [comment]
hmm this is still generating some very weird plots of step vs global step on wandb...

![image](https://github.com/user-attachments/assets/0f1bdfe4-d608-4cf6-86b1-fd7249cb52dd)

**Comment by ffelten** [comment]
You can join here: https://discord.gg/ygmkfnBvKA easier to talk
