### ISSUE TITLE
Parameters of Mujoco experiments

### ISSUE THREAD

**Issue by RuohLiuq** [LucasAlegre/morl-baselines#107]
Dear Authors,

I found that you have run all mujoco experiments (humanoid, halfcheetah, ant, hopper, walker2d.. on https://wandb.ai/openrlbenchmark/MORL-Baselines). However, I can not find the values of \gamma and reference points of each environment. I think these will influence the calculation of hypervolume. I can only find that of hopper and halfcheetah, as you provide example codes for these two mujoco environments.

Thanks for your attention regarding this matter!

**Comment by ffelten** [comment]
Hi,

These hyperparams are listed under the config that you can see on the run overview, e.g.: 
<img width="789" alt="image" src="https://github.com/user-attachments/assets/381683e5-f259-4fab-b3d6-9b83c61ef352">
