### ISSUE TITLE
PGMORL: Wandb keeps asking for token, even if None is passed

### ISSUE THREAD

**Issue by wilhem** [LucasAlegre/morl-baselines#108]
Take this example here: https://github.com/LucasAlegre/morl-baselines/blob/main/examples/pgmorl_halfcheetah.py
and run it (using the very last version of morl-baselines).
Running it in a Colab noteboob, it keeps asking for the Wandb-Token all the time, even when passing None:
```
algo = PGMORL(
    env_id=env_id,
    num_envs=4,
    pop_size=6,
    warmup_iterations=80,
    evolutionary_iterations=20,
    wandb_entity = None,
    num_weight_candidates=7,
    origin=np.array([0.0, -5.0]),
)
```

**Comment by ffelten** [comment]
Hello, 

If you don't want wandb, you can specify `log=False`

**Comment by wilhem** [comment]
Thanks,
I oversaw it.
But it could be more intuitive, since "log" can be even a log on the screen and not a log for Wandb. From the documentation, it was not clear to me
