### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by LucasAlegre** [LucasAlegre/morl-baselines#11]
TODO:

- [x] Fix bug https://github.com/LucasAlegre/morl-baselines/actions/runs/4000541688/jobs/6865789098#step:6:41

**Comment by ffelten** [comment]
Idea: should be able to derive a webpage to read the documentation or something (sphinx or other).

**Comment by ffelten** [comment]
+ examples (from the perf evaluation scripts?)
