### ISSUE TITLE
Add save_freq to CAPQL.train()

### ISSUE THREAD

**Issue by AleNimo** [LucasAlegre/morl-baselines#113]
When training the CAPQL agent, I noticed a drop in the simulation speed when setting `checkpoints = True`. In the code, if `checkpoints = True`, the weights of the nets are stored after every step taken by the agent. A parameter such as `save_freq` could be added to save the net's weights only every `save_freq` number of global steps.

Another improvement would be to save the weights in different files as its being done in the GPI-PD agent, for example.

![imagen](https://github.com/user-attachments/assets/357601a0-ab05-4557-859e-67db04f9108d)

**Comment by LucasAlegre** [comment]
Thanks for spotting this! I will open a PR to fix it :)
