### ISSUE TITLE
Bad results with Chebyshev Scalarisation Function

### ISSUE THREAD

**Issue by Saood1810** [LucasAlegre/morl-baselines#114]
I always seem to get negative eval scalarized returns for MO Q Learning function with Chebyshev scalarisation function. I've been looking at the performance plots on wandb, and it's not good at all.
I tested the MO Q algorithm in Four Room environment, one with linear scalarization and the other with Chebyshev scalarisation. Linear scalarization outperforms by far, giving positive ranging from 0 and ascending to 2.5. On the other hand, the Chebyshev gives 0 and then drops to -6 uniformly. Below is the code I used to implement the functions. 

But in general, Chebyshev hasn't outperformed the linear scalarization and performed similarly or worse with other experiments I've tried, such as in Deep Sea Treasure. From the papers I've read, Chebyshev is supposed to perform much better in most cases.

// MOQ with Linear Scalarisation
from morl_baselines.common.scalarization import weighted_sum
env = MORecordEpisodeStatistics(mo_gym.make("four-room-v0"), gamma=0.99)
eval_env = mo_gym.make("four-room-v0")

weights = np.array([0.33,0.33, 0.3])

agent = MOQLearning(env, scalarization=weighted_sum,gamma=0.99,initial_epsilon=1,final_epsilon=0.1,epsilon_decay_steps=int(1e5), weights=weights, log=True)
agent.train(
        total_timesteps=int(1e5),
        start_time=time.time(),
        eval_freq=100,
        eval_env=eval_env,
    )

//MOQ with Chebyshev

env = MORecordEpisodeStatistics(mo_gym.make("four-room-v0"), gamma=0.99)
eval_env = mo_gym.make("four-room-v0")
scalarization = tchebicheff(tau=4.0, reward_dim=3)
weights = np.array([0.33,0.33, 0.3])

agent = MOQLearning(env, scalarization=scalarization,gamma=0.99,initial_epsilon=1,final_epsilon=0.1,epsilon_decay_steps=int(1e5), weights=weights, log=True)
agent.train(
        total_timesteps=int(1e5),
        start_time=time.time(),
        eval_freq=100,
        eval_env=eval_env,
    )

**Comment by LucasAlegre** [comment]
Hi,

I never tested the Chebyshev function, but I was wondering if this is due to the reference point used. @ffelten implemented a version that automatically adjusts it, but I do not know where it comes from. Maybe we should have the Chebyshev with a fixed reference point, as it is the common approach?

Moreover, which paper are you refering to? Notice that value-based RL with non-linear utility breaks the Bellman equation and there is no guarantees of convergence/optimality.

**Comment by Saood1810** [comment]
Okay so in the paper, Scalarized Multi-Objective Reinforcement Learning: Novel Design Techniques by van Moffaert K et al.  (https://www.researchgate.net/publication/235698665_Scalarized_Multi-Objective_Reinforcement_Learning_Novel_Design_Techniques#:~:text=Various%20strategies%20exist%20for%20addressing,et%20al.%2C%202013)%20.), they proposed the Chebyshev scalarization function. 

Chebyshev Scalarization uses the weighted maximum of the distances from the objective vectors to a reference point, which allows it to explore non-convex parts of the Pareto front. Chebyshev scalarization can thus find a wider range of Pareto optimal solutions, making it more effective in many scenarios. The reference point z_  mentioned in the paper is a parameter constantly adjusted during the learning process by recording the best value so far for each objective o, plus a small constant. So, I think the current implementation in MORL baselines is fine.

It's just that in the paper, the Chebyshev algorithm outperforms the linear scalarization by far. I've tried replicating the experiments in the paper but am not getting those results. So when I tried plotting the learning curve of the Hypervolume during training like the one mentioned in the paper, with the same parameters, the Chebyshev performed terribly, whereas, in the paper, it did quite well. I get similar results for the linear and Chebyshev scalarization.
In other experiments of my own, the performance plots on wandb which is provided by MORL baselines, show results for Chebyshev that are worse than those of linear scalarization. 

I know current MORL algorithms are leaning towards multi-policy solutions. However, the main crux of my research I'm doing is studying the behaviour of single policy methods, specifically the MO Q learning function, one with linear scalarization and one with Chebyshev. I'm trying to motivate why non-linear Chebyshev is a better approach as opposed to linear scalarization by testing the algorithms in various environments.

:)

**Comment by LucasAlegre** [comment]
That is interesting to hear! I suggest you try debugging a bit to confirm that this is not due to any bugs on our side, and perhaps start with a more simpler environment, since four-rooms is actually very large in terms of number of states. Did you try to replicate the results on deep-sea-treasure?

**Comment by Saood1810** [comment]
I've tried it out on deep sea treasure. When I used the evaluation process with the same algorithm parameters adopted in the paper I mentioned, I couldn't replicate the results for the Chebyhsev scalarisationion function. The Chebyshev had similar results to the linear scalarization, which was poor. When I play around with the parameters, I get better results but the linear scalarisationion and Chebyshev always perform similarly. I have yet to have a case where the Chebyshev outperforms the linear scalarzation.

I tried training it now in the DST concave version, but I analysed the plots on wandb (I didn't use the evaluation process from the paper), and I'm getting good results with the linear scalarization. I am getting much higher eval scalarzied returns with the linear(starts at 0 and increases to 30 where it remains constant) while I get negative scores with the Chebyshev( Starts at 0 and goes to as low as -719.38255).This is very strange.
Maybe there could be an issue with the way we log in the Chebyshev scores, more specifically the scalarized returns? That's why it seems poor when, in fact, it could be doing well.

I tried it out on Four-Room as I thought maybe the Chebyshev may perform better in more complex environments, but that's not the case.  I'll let you know if I find anything.

**Comment by LucasAlegre** [comment]
I suggest you stick to deep-sea-treasure for now. Notice that comparing scalarized returns from linear scalarization vs. Chebychev does not make much sense since they are different utility functions. Perhaps check how much reward it is getting for each objective, and if this corresponds to any of the Pareto optimal policies. 

I would suggest checking if the Chebychev utility is being computed correctly and whether there is not a bug in the update of the reference point.

**Comment by Saood1810** [comment]
The main way I am evaluating the aglorithms if from a paper from van Moffaert K. et al.

Each scalarization-based MORL algorithm was tested using different sets of the weights sets ranging from 0 to 1, with a step of 0.1 for each objective, i.e. there are 11 tuples of weights (and experiments) for the worlds with two, respectively. Each scalarized MORL algorithm using a particular weight tuple could be regarded as an individual learning agent.Per iteration, each agent individually tests its learned policy by greedily selecting actions, whereafter each agents' policy is stored in a set. This set is called the Pareto approximation set for a particular iteration number of the learning phase.
This is the way I evaluated and obtained the learning curve wrt hypervolume. The Hypervolume curves for both Linear and Chebyshev were more or less the same.

I will have a look the Chebyshev utility.I didnt realise comparing scalarized returns from linear and non linear is pointless.

I appreciate your advise :)

**Comment by Saood1810** [comment]
Hi,

I believe the implementation of the Chebyshev is fine :)
