### ISSUE TITLE
GPIPDContinousAction: problem with ModelEnv

### ISSUE THREAD

**Issue by osikazuzanna** [LucasAlegre/morl-baselines#115]
Hi! I'm trying to run GPIPD with continuous actions on my custom environment with 4 objectives, but I'm getting an error NotImplementedError coming from the _rollout_dynamics method, specifically from setting the termination_func in the ModelEnv class:

`class ModelEnv:
    """Wrapper for the model to be used as an environment."""

    def __init__(self, model, env_id=None, rew_dim=1):
        """Initialize the environment.

        Args:
            model: model to be used as an environment.
            env_id: environment id.
            rew_dim: reward dimension.
        """
        self.model = model
        self.rew_dim = rew_dim
        if env_id == "Hopper-v2" or env_id == "Hopper-v4" or env_id == "mo-hopper-v4" or env_id == "mo-hopper-2d-v4":
            self.termination_func = termination_fn_hopper
        elif env_id == "HalfCheetah-v2" or env_id == "mo-halfcheetah-v4":
            self.termination_func = termination_fn_false
        elif env_id == "LunarLanderContinuous-v2" or env_id.startswith("mo-lunar-lander"):
            self.termination_func = termination_fn_false
        elif env_id == "ReacherMultiTask-v0" or env_id.startswith("mo-reacher-v"):
            self.termination_func = termination_fn_false
        elif env_id == "MountainCarContinuous-v0" or env_id.startswith("mo-mountaincar"):
            self.termination_func = termination_fn_mountaincar
        elif env_id == "minecart-v0":
            self.termination_func = termination_fn_minecart
        elif env_id == "SEIRsingle-v0":
            self.termination_func = termination_fn_false
        elif env_id == "mo-highway-fast-v0" or env_id == "mo-highway-v0":
            self.termination_func = termination_fn_false
        elif env_id == "deep-sea-treasure-v0":
            self.termination_func = termination_fn_dst
        else:
            raise NotImplementedError
`

Do I have to implement this function by myself or is there some error with initiating my environt?

Thanks for all your work on the rep and the continuous support!

**Comment by LucasAlegre** [comment]
Hi!

Yes, you need to implement the termination function of your environment, or use `termination_fn_false` if your environment has no terminal states.

**Comment by osikazuzanna** [comment]
Perfect, thanks!

**Comment by nkirschi** [comment]
@LucasAlegre How do I implement my env's termination function? It seems hardcoded into this `ModelEnv` class... For now,  my workaround is to set my env's ID to `"mo-highway-v0"` to achieve `termination_fn_false` to be configured.
