### ISSUE TITLE
Logging the front in wandb

### ISSUE THREAD

**Issue by osikazuzanna** [LucasAlegre/morl-baselines#117]
Hi! I've been working with my custom environments and trying to connect them to the algorithms from morl-baselines (continuous action and state space). I have environments with varying objective numbers (2-6). I ran a couple of experiments with default params just to see how my environments would behave (using your run_experiment.py script), but everytime I try training on an environment with more than 2 objectives and log it in wandb, the table _runs.summary["eval/front"]_ with the objective values has only two objective. However, the return plots are for every objective. I created a wandb report with an example so you can take a look [here](https://wandb.ai/osikaz/MORL-Baselines/reports/Untitled-Report--Vmlldzo5Mjc4MTYy?accessToken=w07ib8xramhc0532fch5nt1k4ynb6rv66nxoe7pfwrk9wu957crnfjop3v6mkk8d) . This is an environment with 4 objectives. Am I doing something wrong when running the experiments or just not understanding the outputs properly?

Also, would it be possible to get the config files for hyperparameter tuning for PCN, CapQL and GPI-PD/LS? The default ones don't seem to be working well 😅

Again, thank you for your support, I would be lost without your resources!

**Comment by LucasAlegre** [comment]
Hi @osikazuzanna,

Regarding the table `runs.summary["eval/front"]`, I don't know why wandb is only showing the first two objectives by default, but you can add the rest clicking on the "Columns" buttom (see the image below)
![image](https://github.com/user-attachments/assets/3289eda5-0ff2-4d0f-beb9-115d3d15a6aa)

We don't have config files for hyperparameter tuning, but I would suggest you try GPI-LS first, and depending on your results I would not mind taking a look and suggesting some changes.

I am glad our libraries are being useful :)

**Comment by osikazuzanna** [comment]
Yes, thank you!
