### ISSUE TITLE
Benchmark algorithms + wandb reports

### ISSUE THREAD

**Issue by LucasAlegre** [LucasAlegre/morl-baselines#12]

**Comment by ffelten** [comment]
- [ ] Define acceptable performances (+ on which metrics)
- [ ] Define which algo should be tested on which environments
- [ ] Create scripts for running the whole thing

**Comment by PatrickYanZ** [comment]
it will be nice.  Now, I rely on the logs from wandb and the python crawler grabs data and puts it into the pandas data frame. It is much easier to export step, `total reward`, `discount reward` to output files. wandb has some tools to implement this.

**Comment by ffelten** [comment]
see also #43

**Comment by ffelten** [comment]
See https://wandb.ai/openrlbenchmark/MORL-Baselines?workspace
