### ISSUE TITLE
Why does the PQL not run in Four Room?

### ISSUE THREAD

**Issue by Saood1810** [LucasAlegre/morl-baselines#123]
Hi

Why does the PQL not run in the Four-Room environment since it has been designed to work in deterministic, episodic environments?

**Comment by ffelten** [comment]
Hi @Saood1810,

PQL is a tabular algorithm. Therefore, I doubt it will scale to the number of state-action pairs that four rooms have -- the problem is just too big.

**Comment by Saood1810** [comment]
Thank you for the response!
