### ISSUE TITLE
ModuleNotFoundError: No module named 'mo_gymnasium.wrappers'

### ISSUE THREAD

**Issue by hejincheng-bit** [LucasAlegre/morl-baselines#130]

**Comment by LucasAlegre** [comment]
Did you install the most recent version of mo-gymnasium?

**Comment by hejincheng-bit** [comment]
Yes, I have installed mo-gymnasium==0.3.4，and my python version is 3.7.16，I don't know if it's a version incompatibility issue

**Comment by LucasAlegre** [comment]
morl-baselines requires mo-gymnasium>=1.3.0.
Moreover, gymnasium no longer supports python 3.7. You need to use a newer version of python and update the libraries.
