### ISSUE TITLE
Migration from gym to gymnasium (also from mo-gym to mo-gymnasium)

### ISSUE THREAD

**Issue by ChrisZonghaoLi** [LucasAlegre/morl-baselines#20]
As the new mo-gymnasium been released (0.3.0), I think the library names here for gym and mo-gym should also be updated to gymnasium and mo-gymnasim, respectively. Otherwise issues like `ModuleNotFoundError: No module named 'gym'` will pop up. @LucasAlegre

**Comment by ChrisZonghaoLi** [comment]
Okay I though I did installed the `morl-baselines` but I actually didn't after I switched to a new environment. Nevermind I think it is all good here.

**Comment by ffelten** [comment]
Hello Chris, we are in the process of migrating baselines to MO-Gymnasium now. It should be done by the end of the week hopefully.
