### ISSUE TITLE
Custom Enviroment

### ISSUE THREAD

**Issue by avarbella** [LucasAlegre/morl-baselines#50]
Hi I'm a new user, I will like to apply MORL to my custom problem, is the library easy to adapt to a custom environment?

**Comment by ffelten** [comment]
Hello there and welcome!

The library follows the [MO-Gymnasium](https://mo-gymnasium.farama.org/) API. Thus, if your environment respects the specifications, there should be an algorithm compatible with it in the lib.

Don't hesitate to join our discord channel (https://discord.gg/ygmkfnBvKA) as I'm sure you will have further questions :-).

**Comment by avarbella** [comment]
Thank you I'll join :)
