### ISSUE TITLE
Visualizing the generated Pareto front 

### ISSUE THREAD

**Issue by xwen24** [LucasAlegre/morl-baselines#73]
Hello, thanks so much for sharing the codes!

I am a beginner in multi-objective reinforcement learning and would like to apply CAPQL in my domain. I have three questions: 

(1) is the CAPQL code able to optimize three or more objectives currently?
(2) how to visualize the finally generated Pareto front?
(3) it that possible to visualize the Pareto front with three objectives?

**Comment by ffelten** [comment]
@xwen24 is this solved?

**Comment by xwen24** [comment]
Sorry for the late reply.

Thanks so much for your help! My porblme has been solved.

**Comment by xwen24** [comment]
Sorry to bother your again. I am just wondering if you plan to add more MORL algorithms in the future, such as "Distributional Pareto-Optimal Multi-Objective Reinforcement Learning" by Cai et al. in NeurIPS 2023.

**Comment by ffelten** [comment]
Hi @xwen24,

Unfortunately, on my side I will not have time to do this in the following months but maybe later next year. However, in the meanwhile we are always happy to receive new contributions :-).

**Comment by xwen24** [comment]
Hi @ffelten,

Based on your paper "A Toolkit for Reliable Benchmarking and Research in Multi-Objective Reinforcement Learning" in NeurIPS 2023, I will use GPI-PD as it mostly outperforms CAPQL and others when dealing with continuous action spaces. I am wondering if the GPI-PD code able to optimize 4-6 objectives currently.

Thanks.
