### ISSUE TITLE
how to run the file named gpi_pd_hopper.py in the example folder?

### ISSUE THREAD

**Issue by man469** [LucasAlegre/morl-baselines#79]
I try to run the code gpi_pd_hopper.py in the example folder, but got the following error:
ERROR: The function received no value for the required argument: algo
Usage: gpi_pd_minecart.py ALGO GPI_PD G <flags>
  optional flags:        --timesteps_per_iter | --seed

For detailed information on this command, run:
  gpi_pd_minecart.py --help
An exception has occurred, use %tb to see the full traceback.

It seems that I have to pass some value to algo, could anyone give more instructions about how to run this code? Thank you very much!

**Comment by LucasAlegre** [comment]
Hi,

You have to pass algo="gpi-ls". See the documentation to check the parameters of each algorithm. You can also see in the gpi_pd_hopper.py file the parameters of this script.

**Comment by man469** [comment]
Thank you very much for your help!
